### ISSUE TITLE
Gracefully handle when journ.cfg.json not found in directory

### ISSUE THREAD

**Issue by kyledinh** [kyledinh/journ#2]
* Maybe it should search for `journ.cfg.json` in local directory, then home directory, then display gracefully error message to user with fix example

```
kyle@KMBP:~/code/toolkit$ journ new
===== A New Day ====
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './journ.cfg.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.module.exports.recordLog (/usr/local/lib/node_modules/journ/lib/api.js:163:29)
    at Object.newDay (/usr/local/lib/node_modules/journ/journ.js:39:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/journ/journ.js:131:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by kyledinh** [comment]
[ ] rename the the config file as ".journ.cfg.json" as a  hidden file in Finder
[ ] search working directory, then in home directory
