### ISSUE TITLE
"journ new" needs to ensure new week-##.md file is created.

### ISSUE THREAD

**Issue by kyledinh** [kyledinh/journ#4]
==== weekSummary ====
[ '/Users/kyle/journ/preamble.md',
  '/Users/kyle/journ/task.md',
  '/Users/kyle/journ/today.md' ]
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/kyle/journ/week-28.md'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.truncateSync (fs.js:847:15)
    at weekSummary (/usr/local/lib/node_modules/journ/lib/api.js:117:12)
    at Object.module.exports.weekSummary (/usr/local/lib/node_modules/journ/lib/api.js:137:5)
    at Object.weekSummary (/usr/local/lib/node_modules/journ/journ.js:53:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/journ/journ.js:132:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by kyledinh** [comment]
fixed with v0.3.3

fs.closeSync(fs.openSync(weekSummaryMd, 'w'));
